name: Salesforce Deployment

on:
  push:
    branches:
      - main
      - "feature/*"
      - "bugfix/*"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install Salesforce CLI
        uses: salesforcecli/install@v1

      - name: Authenticate Salesforce Org
        shell: bash
        run: |
          echo "${{ secrets.SFDX_AUTH_FILE }}" > authFile.json
          sf org login sfdx-url --sfdx-url-file authFile.json -a projectLog

      - name: Deploy to Salesforce
        run: |
          sf project deploy start -o projectLog
